[build-system]
requires = ["setuptools>=61.0", "django>=4.2"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
line_length = 99

[tool.black]
line-length = 99
exclude = '''
/(
    \.git
  | \.tox
  | \.venv
  | dist
)/
'''
